# Generated by Django 3.1.3 on 2020-11-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('image', models.ImageField(default='products/shoe.jpg', upload_to='products')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('category', models.CharField(choices=[('sh', 'Shoes'), ('Ha', 'Hats'), ('P', 'Pants')], max_length=100)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=100)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
