# Generated by Django 3.1.3 on 2020-11-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_order_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
