# Generated by Django 3.1.3 on 2020-12-17 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_orderproduct_purchased'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='customer',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.orderproduct')),
            ],
        ),
    ]
