# Generated by Django 3.1.3 on 2020-12-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='added_to_cart',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='purchased',
        ),
    ]
