# Generated by Django 3.1.3 on 2020-12-27 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_orderproduct_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='products.orderproduct'),
            preserve_default=False,
        ),
    ]
