# Generated by Django 3.1.3 on 2020-12-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='removed_from_cart',
            field=models.BooleanField(default=False),
        ),
    ]
