# Generated by Django 3.1.3 on 2020-12-31 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20201230_0935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OPro',
        ),
    ]
